### ISSUE TITLE
Error while fetching smartbike data.

### ISSUE THREAD

**Issue by christof62** [ReneNulschDE/ha-mysmartbike#4]
HA Version:  2024.5.3

I checked the API response. The data does not include location information. 
```
// 20240515153212
// https://my-smartbike.com/api/v1/objects/me?limit=5

{
  "status": 200,
  "code": "OK",
  "success": true,
  "data": [
    {
      "id": 189,
      "alias": "ORBEA Gain 170 EU",
      "serial": "OB",
      "object_status": "SOLD",
      "diagnosis_status": "ACTIVE",
      "manufacture_date": "2023-07-06 18:41:56",
      "activation_date": "2024-04-18 10:19:15",
      "mac_address": "D2:4D:C9:46:3B:8E",
      "odometry": 400000,
      "diagnosed": true,
      "diagnosed_at": "2024-05-15 13:16:47",
     ...
```

Debug log:
```
2024-05-15 15:04:58.134 DEBUG (MainThread) [custom_components.mysmartbike.webapi] login: Start
2024-05-15 15:04:58.134 DEBUG (MainThread) [custom_components.mysmartbike.webapi] login: Token not expired
2024-05-15 15:04:58.134 DEBUG (MainThread) [custom_components.mysmartbike.coordinator] Start save_token
2024-05-15 15:04:58.135 DEBUG (MainThread) [custom_components.mysmartbike.coordinator] _async_update_data: started
2024-05-15 15:04:58.422 ERROR (MainThread) [custom_components.mysmartbike.coordinator] Unexpected error fetching mysmartbike data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mysmartbike/coordinator.py", line 71, in _async_update_data
    devices = await self.webapi.get_device_list()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mysmartbike/webapi.py", line 95, in get_device_list
    return await self._build_device_list(_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mysmartbike/webapi.py", line 173, in _build_device_list
    datetime.strptime(rbike.get("last_position_date"), "%Y-%m-%d %H:%M:%S"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not None
2024-05-15 15:04:58.474 DEBUG (MainThread) [custom_components.mysmartbike.coordinator] Finished fetching mysmartbike data in 0.340 seconds (success: False)
```

Thanks,
Christof

**Comment by ReneNulschDE** [comment]
Published a new release. This release is just fixing the last_position_date bug. However, Mahle made more changes to their API and the Device Tracker is still broken. This will be handled in an later release in June.

**Comment by ReneNulschDE** [comment]
Published a new release. This adds the device tracker again.
